services:
  backend:
    image: wkdlrn/ml-back:test
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DB_USER=root
      - DB_PASSWORD=qwer1234
      - DB_URL=jdbc:mariadb://db:3306/web
  db:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=qwer1234
      - MARIADB_DATABASE=web
    volumes:
      - backdb:/var/lib/mysql
volumes:
  backdb: