apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  labels:
    type: database
spec:
  replicas: 1
  selector:
    matchLabels:
      type: db
  template: 
    metadata:
      labels:
        type: db
    spec:
      containers:
        - name: master-db-container
          image: mariadb:latest
          volumeMounts:
            - name: db-vol
              mountPath: /var/lib/mysql/
          envFrom:
          - configMapRef:
              name: db-cm
          ports:
          - containerPort: 3306
      volumes:
        - name: db-vol
          persistentVolumeClaim:
            claimName: db-pvc
