spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test4
    username: lee
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create  # (none, validate, update, create, create-drop ? ??)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  # ????: ??? H2 ?? ? ??
  # h2:
  #   console:
  #     enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
