spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXP}

portone:
  api_secret: ${PORT0NE_API_SECRET}

aes:
  secret: ${AES_SECRET}

file:
  upload-dir: ${FILEPATH}
  
server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  security:
    enabled: false
