spring:
#  profiles:
#    active: dev
  data:
    elasticsearch:
      uris: ${ES_URI}
      username: ${ES_USERNAME}
      password: ${ES_PASSWORD}
#      ssl:
#        certificate: file:/es-ca.crt   #src/main/resources 밑에 넣으면 classpath로 인식됨
#        verification-mode: certificate

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          localhost: client.local.dev

  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: file:${UPLOAD_DIR}/

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXP}

portone:
  api_secret: ${PORT0NE_API_SECRET}

aes:
  secret: ${AES_SECRET}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.data.elasticsearch: DEBUG

file:
  upload-dir: ${UPLOAD_DIR}

server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      show-components: always
  security:
    enabled: false
  health:
    db:
      enabled: true
    mail:
      enabled: false
    diskspace:
      enabled: false
    ping:
      enabled: false
    ssl:
      enabled: false

springdoc:
  api-docs:
    path: /docs/v3/api-docs

  swagger-ui:
    url: /docs/v3/api-docs
    path: /docs/swagger-ui

openai:
  api-key: ${api_key}