spring:
  profiles:
    active: dev  # ⭐️ 현재 실행 프로파일 (dev / prod)

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # (none, validate, update, create, create-drop ? ??)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  # ????: ??? H2 ?? ? ??
  # h2:
  #   console:
  #     enabled: true
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXP}

portone:
  api_secret: ${PORT0NE_API_SECRET}

aes:
  secret: ${AES_SECRET}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
