apiVersion: batch/v1
kind: CronJob
metadata:
  name: settlement-batch-cronjob
spec:
  schedule: "* 1 * * *"  # 🔄 매 1시마다 실행
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: settlement-job
              image: k6kjun/mlbatch:latest
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: batch-cm